# Generated by Django 5.2.14 on 2026-09-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "subject",
                    models.CharField(
                        default="Reminder: submit your SCD activity report",
                        max_length=200,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="Hello {{recipient_name}},\n\nThis is a reminder to record your recent work in the SCD Activity Reporting\nSystem. Entries take only a few minutes and give the division an accurate\npicture of where effort is going.\n\n**Your last entry:** {{last_entry_summary}}\n\nPlease add an entry for the current reporting period here:\n\n{{new_entry_url}}\n\nYou can review everything you have already submitted here:\n\n{{my_entries_url}}\n\nThank you,\n{{sender_name}}\n",
                        help_text="Markdown. Supports {{placeholder}} tokens — see the placeholder reference.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Used when a send or schedule does not name a template.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_templates_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Template",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 weeks"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=4,
                        help_text="Used by the weekly and biweekly frequencies.",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Used by the monthly frequency. Clamped to the length of each month.",
                    ),
                ),
                (
                    "send_time",
                    models.TimeField(
                        help_text="Local wall-clock time in the timezone below."
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Chicago",
                        help_text="IANA timezone name, e.g. America/Chicago.",
                        max_length=64,
                    ),
                ),
                (
                    "only_stale",
                    models.BooleanField(
                        default=True,
                        help_text="Skip people who already have a recent entry.",
                    ),
                ),
                (
                    "stale_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="How many days without an entry counts as stale.",
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Recipients are resolved from this user's role and scope at send time.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="reminders.remindertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Schedule",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=500)),
                (
                    "last_entry_at",
                    models.DateField(
                        blank=True,
                        help_text="Period end of the recipient's most recent entry when the reminder was sent.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for a scheduled send.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for an interactive send.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sends",
                        to="reminders.reminderschedule",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sends",
                        to="reminders.remindertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Log Entry",
                "verbose_name_plural": "Reminder Log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reminderschedule",
            index=models.Index(
                fields=["is_enabled", "next_run_at"],
                name="reminders_r_is_enab_7efffb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminderlog",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="reminders_r_recipie_6b66af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminderlog",
            index=models.Index(
                fields=["status", "-created_at"], name="reminders_r_status_bd75e9_idx"
            ),
        ),
    ]
