# Generated by Django 5.2.14 on 2026-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                    ("login", "Logged in"),
                    ("logout", "Logged out"),
                    ("export", "Exported"),
                    ("reminder", "Reminder sent"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
